name: debrid_player
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Build configuration flags
move_release_apk_to_desktop: true
version: 1.0.7


environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  scrollable_positioned_list:
  http:
  shared_preferences:
  sqflite:
  path:
  dio:
  path_provider:
  build_runner:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation: ^4.9.0
  flutter_hooks:
  flutter_image_compress:
  android_intent_plus:
  speech_to_text:
  fluttertoast:
  flutter_broadcasts:
    git:
      url: https://github.com/KRTirtho/flutter_broadcasts.git
      ref: main
  webfeed:
  package_info_plus:
  url_launcher:
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator:
  freezed:
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/missing_poster.webp